### ISSUE TITLE
No such file or directory "data/data.json"

### ISSUE THREAD

**Issue by brannondorsey** [nbriz/beatripper#1]
Tried to get this up and running with:

`cd app`
`npm install`
`nw .`

And getting the error:

```
[84278:0110/191638:ERROR:nw_shell.cc(335)] Error: ENOENT: no such file or directory, open 'data/data.json'
    at Error (native)
    at Object.fs.openSync (fs.js:540:18)
    at Object.fs.readFileSync (fs.js:392:15)
    at Object.readFileSync (/Users/bdorse/Documents/Code/beatripper/app/node_modules/jsonfile/index.js:31:20)
    at file:///Users/bdorse/Documents/Code/beatripper/app/main.js:6:21
[84278:0110/191638:INFO:CONSOLE(540)] "Uncaught Error: ENOENT: no such file or directory, open 'data/data.json'", source: fs.js (540)
```

Further inspection of the `.gitignore` would suggest that some contents from the `app/data` folder are being ignored, but may be necessary to run the app. @nbriz Any chance those files could be added to the repository? Also, am I correct in assuming that this app only works with NW, and not Node itself (as there seems to be DOM manipulation in main.js)?

**Comment by brannondorsey** [comment]
Ah, a quick look at `data/NFO` seems to offer an explanation. Trying this now.

**Comment by brannondorsey** [comment]
Hmm... created an `app/data/data.json` file with these contents:

```
{
    "rythms" : []
}
```

and am no longer receiving the above error, but for some reason now `nw .` doesn't launch/create an NW window, nor does it provide any error in the console. It simply leaves the processes running without actually creating an app window. I've never run into this before with NW. Any thoughts?

**Comment by nbriz** [comment]
yea i gotta put some build instructions && use instructions ( for once its running ), haven't gotten around to it yet, but yea as u noticed u got to create the aforementioned data.json file in the data folder + if u want to use the sublime-project shortcuts you've got to npm install in both the app/ and tools/ directory && change the path in the .sublime-project file to match urs + in sublime change to Tools > Build System > Branger_Briz ( though that build system has really only been implemented for linux ) ... all that said, u're using ur global nw right? so non of that should be an issue?

**Comment by vazw** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
Ezneh, @KenMan79, @ltungv, @TristanCacqueray, @gruszkakarol, @Harry-tellah, @henryhawke, @lparolari, @ugjka, @srmullen, @Beyondtarun, @attemanninen, @Kongduino, @sdiehl, @Githiora, @vandrito, @YuheiNakasaka, @elivolunteer, @ibcaos, @kobbin003
